'use client';

import { useState } from 'react';
import { AcademicCapIcon, MapPinIcon, ClockIcon } from '@heroicons/react/24/outline';

interface TransportReport {
  id: string;
  reportType: string;
  date: string;
  details: string;
  generatedBy: string;
}

const mockTransportReports: TransportReport[] = [
  { id: 'TR-001', reportType: 'Route Efficiency', date: '2024-07-30', details: 'Analysis of fuel consumption and time taken for all routes.', generatedBy: 'Admin' },
  { id: 'TR-002', reportType: 'Student Pick-up/Drop-off Times', date: '2024-07-29', details: 'Detailed log of student timings for Route 3.', generatedBy: 'Operations' },
  { id: 'TR-003', reportType: 'Vehicle Maintenance Log', date: '2024-07-28', details: 'Records of all maintenance activities for Bus A.', generatedBy: 'Maintenance' },
];

export default function TransportReportsPage() {
  const [reports, setReports] = useState(mockTransportReports);

  const handleViewReport = (reportId: string) => {
    alert(`Viewing report ${reportId}`);
    // In a real application, this would navigate to a detailed report view or open a modal
  };

  return (
    <div>
      <h1 className="text-3xl font-bold mb-6">Transport Reports</h1>
      <p className="text-gray-600 mb-4">Generate and view various reports related to school transport.</p>

      <div className="bg-white p-8 rounded-lg shadow-lg">
        <table className="min-w-full text-left">
          <thead className="border-b bg-gray-50">
            <tr>
              <th className="px-6 py-3 text-sm font-medium text-gray-700">Report ID</th>
              <th className="px-6 py-3 text-sm font-medium text-gray-700">Report Type</th>
              <th className="px-6 py-3 text-sm font-medium text-gray-700">Date</th>
              <th className="px-6 py-3 text-sm font-medium text-gray-700">Generated By</th>
              <th className="px-6 py-3 text-sm font-medium text-gray-700">Actions</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report.id} className="border-b hover:bg-gray-50">
                <td className="px-6 py-4 text-sm font-medium text-gray-900">{report.id}</td>
                <td className="px-6 py-4 text-sm text-gray-900">{report.reportType}</td>
                <td className="px-6 py-4 text-sm text-gray-900">{report.date}</td>
                <td className="px-6 py-4 text-sm text-gray-900">{report.generatedBy}</td>
                <td className="px-6 py-4 text-sm">
                  <button
                    onClick={() => handleViewReport(report.id)}
                    className="text-indigo-600 hover:text-indigo-900 flex items-center"
                  >
                    View Details
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
